# Generated by Django 5.1.7 on 2025-03-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_paciente_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cedula',
            new_name='numero_identidad',
        ),
    ]
