# Generated by Django 3.2.6 on 2025-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('peso_archivo', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado_analisis', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
