# Generated by Django 5.1.7 on 2025-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=300)),
                ('duracion', models.IntegerField()),
                ('hora_inicio', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=300)),
                ('causa', models.CharField(max_length=350)),
                ('hora_inicio', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescripcionMedicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=300)),
                ('medicamento', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eeg',
            name='comentarios',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
